// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexico

package analizadores;
import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\0"+
    "\1\6\1\0\1\7\2\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\12\21\1\0\1\22"+
    "\2\0\1\23\1\24\1\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\2\37\1\53\1\37\1\0\1\54\2\0"+
    "\1\55\1\0\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\2\37\1\53\1\37\1\56\1\57\1\60\7\0\1\3"+
    "\71\0\1\61\2\0\1\61\155\0\2\62\115\0\1\63"+
    "\u01a8\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\20\1\1\20\1\21\1\22\1\0\1\23"+
    "\2\0\1\24\30\0\1\25\5\0\1\26\2\0\1\23"+
    "\1\24\1\0\2\2\1\27\1\30\4\0\1\31\5\0"+
    "\1\32\13\0\1\33\1\34\10\0\1\35\5\0\1\36"+
    "\24\0\1\37\1\40\6\0\1\2\12\0\1\41\5\0"+
    "\1\42\1\43\4\0\1\44\1\45\6\0\1\46\2\0"+
    "\1\47\15\0\1\50\5\0\1\51\2\0\1\52\1\0"+
    "\1\53\4\0\1\54\15\0\1\55\10\0\1\56\2\0"+
    "\1\57\3\0\1\60\1\61\1\0\1\62\3\0\1\63"+
    "\2\0\1\64\1\0\1\65\2\0\1\66\1\67\1\70"+
    "\2\0\1\71\5\0\1\72\1\73\4\0\1\74\4\0"+
    "\1\75\10\0\1\76\1\0\1\77\1\100\4\0\1\101"+
    "\1\102\4\0\1\103\1\104\1\105\1\0\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[308];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\234\0\64\0\320\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\u0104\0\u0138\0\64"+
    "\0\64\0\64\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410"+
    "\0\u0444\0\u0478\0\64\0\64\0\64\0\234\0\64\0\u04ac"+
    "\0\u04e0\0\64\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618"+
    "\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8"+
    "\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958"+
    "\0\u098c\0\u09c0\0\64\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4"+
    "\0\64\0\u0af8\0\u0b2c\0\234\0\u04e0\0\u0b60\0\64\0\u0b94"+
    "\0\u05b0\0\64\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc"+
    "\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c"+
    "\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c"+
    "\0\64\0\64\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144"+
    "\0\u1178\0\u11ac\0\64\0\u11e0\0\u1214\0\u1248\0\u127c\0\u12b0"+
    "\0\64\0\u12e4\0\u1318\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c"+
    "\0\u1450\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u1554\0\u1588\0\u15bc"+
    "\0\u15f0\0\u1624\0\u1658\0\u168c\0\u16c0\0\64\0\64\0\u16f4"+
    "\0\u1728\0\u175c\0\u1790\0\u17c4\0\u17f8\0\u17f8\0\u182c\0\u1860"+
    "\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964\0\u1998\0\u19cc\0\u1a00"+
    "\0\64\0\u1a34\0\u1a68\0\u1a9c\0\u1ad0\0\u1b04\0\64\0\u1b38"+
    "\0\u1b6c\0\u1ba0\0\u1bd4\0\u1c08\0\u1c3c\0\u1c70\0\u1ca4\0\u1cd8"+
    "\0\u1d0c\0\u1d40\0\u1d74\0\u1da8\0\64\0\u1ddc\0\u1e10\0\64"+
    "\0\u1e44\0\u1e78\0\u1eac\0\u1ee0\0\u1f14\0\u1f48\0\u1f7c\0\u1fb0"+
    "\0\u1fe4\0\u2018\0\u204c\0\u2080\0\u20b4\0\64\0\u20e8\0\u211c"+
    "\0\u2150\0\u2184\0\u21b8\0\64\0\u21ec\0\u2220\0\64\0\u2254"+
    "\0\64\0\u2288\0\u22bc\0\u22f0\0\u2324\0\64\0\u2358\0\u238c"+
    "\0\u23c0\0\u23f4\0\u2428\0\u245c\0\u2490\0\u24c4\0\u24f8\0\u252c"+
    "\0\u2560\0\u2594\0\u25c8\0\64\0\u25fc\0\u2630\0\u2664\0\u2698"+
    "\0\u26cc\0\u2700\0\u2734\0\u2768\0\64\0\u279c\0\u27d0\0\64"+
    "\0\u2804\0\u2838\0\u286c\0\64\0\64\0\u28a0\0\64\0\u28d4"+
    "\0\u2908\0\u293c\0\64\0\u2970\0\u29a4\0\u29d8\0\u2a0c\0\64"+
    "\0\u2a40\0\u2a74\0\64\0\64\0\64\0\u2aa8\0\u2adc\0\64"+
    "\0\u2b10\0\u2b44\0\u2b78\0\u2bac\0\u2be0\0\64\0\64\0\u2c14"+
    "\0\u2c48\0\u2c7c\0\u2cb0\0\64\0\u2ce4\0\u2d18\0\u2d4c\0\u2d80"+
    "\0\64\0\u2db4\0\u2de8\0\u2e1c\0\u2e50\0\u2e84\0\u2eb8\0\u2eec"+
    "\0\u2f20\0\64\0\u2f54\0\64\0\64\0\u2f88\0\u2fbc\0\u2ff0"+
    "\0\u3024\0\64\0\64\0\u3058\0\u308c\0\u30c0\0\u30f4\0\64"+
    "\0\64\0\64\0\u3128\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[308];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\2\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\2\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\2\1\31\1\32\3\2\1\33\1\34"+
    "\1\35\1\36\1\2\1\37\1\40\2\2\1\41\2\2"+
    "\1\42\1\43\1\2\1\44\1\45\1\32\1\40\65\0"+
    "\1\3\2\0\2\3\56\0\2\46\1\0\3\46\1\47"+
    "\45\46\1\50\7\46\1\51\2\0\3\51\1\0\1\51"+
    "\1\52\43\51\1\53\7\51\13\0\1\54\4\0\1\55"+
    "\62\0\1\56\1\0\1\17\104\0\1\57\64\0\1\60"+
    "\45\0\1\61\15\0\1\62\51\0\1\63\70\0\1\64"+
    "\3\0\1\65\4\0\1\66\13\0\1\66\25\0\1\67"+
    "\7\0\1\70\13\0\1\71\10\0\1\70\26\0\1\72"+
    "\77\0\1\73\1\74\46\0\1\75\3\0\1\76\3\0"+
    "\1\77\5\0\1\100\16\0\1\77\44\0\1\101\5\0"+
    "\1\102\60\0\1\103\6\0\1\104\33\0\1\105\15\0"+
    "\1\106\51\0\1\107\63\0\1\110\3\0\1\111\24\0"+
    "\1\111\32\0\1\112\57\0\27\113\10\0\2\46\1\0"+
    "\3\46\1\114\45\46\1\50\7\46\10\0\1\52\61\0"+
    "\1\51\1\0\1\115\31\0\1\51\5\0\1\51\13\0"+
    "\13\54\1\116\50\54\2\55\1\117\1\0\1\120\57\55"+
    "\5\0\1\121\13\0\1\121\35\0\1\121\34\0\1\122"+
    "\76\0\1\123\50\0\1\124\15\0\1\125\56\0\1\126"+
    "\1\127\76\0\1\130\37\0\1\131\102\0\1\132\70\0"+
    "\1\133\46\0\1\134\65\0\1\135\63\0\1\136\50\0"+
    "\1\137\17\0\1\140\13\0\1\140\44\0\1\141\46\0"+
    "\1\142\3\0\1\143\1\0\1\144\24\0\1\144\54\0"+
    "\1\145\52\0\1\146\5\0\1\147\44\0\1\150\62\0"+
    "\1\151\103\0\1\152\54\0\1\153\71\0\1\154\13\0"+
    "\1\154\46\0\1\155\65\0\1\156\57\0\1\157\3\0"+
    "\1\160\46\0\1\161\76\0\1\162\36\0\1\113\3\0"+
    "\27\113\1\0\1\163\6\0\13\164\1\165\4\164\1\117"+
    "\43\164\2\0\1\117\121\0\1\166\54\0\1\167\57\0"+
    "\1\170\101\0\1\171\75\0\1\172\46\0\1\173\52\0"+
    "\1\174\77\0\1\175\50\0\1\176\4\0\1\177\24\0"+
    "\1\177\50\0\1\200\13\0\1\200\55\0\1\201\35\0"+
    "\1\202\65\0\1\203\102\0\1\204\61\0\1\205\63\0"+
    "\1\206\63\0\1\207\44\0\1\210\77\0\1\211\63\0"+
    "\1\212\63\0\1\213\62\0\1\214\52\0\1\215\67\0"+
    "\1\216\24\0\1\216\26\0\1\217\67\0\1\220\63\0"+
    "\1\221\75\0\1\222\71\0\1\223\42\0\1\224\33\0"+
    "\13\54\1\116\4\54\1\225\56\54\1\116\4\54\1\226"+
    "\43\54\31\0\1\227\74\0\1\230\50\0\1\231\100\0"+
    "\1\232\5\0\1\233\54\0\1\234\71\0\1\235\54\0"+
    "\1\236\56\0\1\237\24\0\1\237\34\0\1\240\73\0"+
    "\1\241\52\0\1\242\6\0\1\243\2\0\1\244\2\0"+
    "\1\245\13\0\1\245\35\0\1\246\24\0\1\246\47\0"+
    "\1\247\42\0\1\250\73\0\1\251\24\0\1\251\32\0"+
    "\1\252\63\0\1\253\67\0\1\254\24\0\1\254\47\0"+
    "\1\255\63\0\1\256\45\0\1\257\103\0\1\260\61\0"+
    "\1\261\57\0\1\262\71\0\1\263\61\0\1\264\57\0"+
    "\1\265\46\0\1\266\56\0\1\164\70\0\1\267\63\0"+
    "\1\270\106\0\1\271\40\0\1\272\63\0\1\273\113\0"+
    "\1\274\56\0\1\275\42\0\1\276\66\0\1\277\102\0"+
    "\1\300\63\0\1\301\43\0\1\302\3\0\1\303\24\0"+
    "\1\303\26\0\1\304\67\0\1\305\3\0\1\306\24\0"+
    "\1\306\44\0\1\307\75\0\1\310\47\0\1\311\63\0"+
    "\1\312\71\0\1\313\13\0\1\313\43\0\1\314\75\0"+
    "\1\315\63\0\1\316\51\0\1\317\66\0\1\320\60\0"+
    "\1\321\47\0\1\322\71\0\1\323\24\0\1\323\43\0"+
    "\1\324\51\0\1\325\75\0\1\326\52\0\1\327\100\0"+
    "\1\330\55\0\1\331\52\0\1\332\61\0\1\333\67\0"+
    "\1\334\63\0\1\335\57\0\1\336\100\0\1\337\71\0"+
    "\1\340\44\0\1\341\100\0\1\342\50\0\1\343\72\0"+
    "\1\344\66\0\1\345\53\0\1\346\24\0\1\346\32\0"+
    "\1\347\57\0\1\350\101\0\1\351\63\0\1\352\45\0"+
    "\1\353\73\0\1\354\24\0\1\354\47\0\1\355\42\0"+
    "\1\356\67\0\1\357\100\0\1\360\42\0\1\361\101\0"+
    "\1\362\63\0\1\363\66\0\1\364\64\0\1\365\13\0"+
    "\1\365\46\0\1\366\55\0\1\367\52\0\1\370\77\0"+
    "\1\371\62\0\1\372\46\0\1\373\107\0\1\374\63\0"+
    "\1\375\60\0\1\376\57\0\1\377\67\0\1\u0100\72\0"+
    "\1\u0101\63\0\1\u0102\55\0\1\u0103\13\0\1\u0103\25\0"+
    "\1\u0104\104\0\1\u0105\63\0\1\u0106\56\0\1\u0107\70\0"+
    "\1\u0108\57\0\1\u0109\52\0\1\u010a\67\0\1\u010b\24\0"+
    "\1\u010b\31\0\1\u010c\103\0\1\u010d\55\0\1\u010e\52\0"+
    "\1\u010f\107\0\1\u0110\56\0\1\u0111\50\0\1\u0112\24\0"+
    "\1\u0112\36\0\1\u0113\24\0\1\u0113\44\0\1\u0114\51\0"+
    "\1\u0115\102\0\1\u0116\55\0\1\u0117\64\0\1\u0118\63\0"+
    "\1\u0119\66\0\1\u011a\57\0\1\u011b\46\0\1\u011c\71\0"+
    "\1\u011d\63\0\1\u011e\100\0\1\u011f\61\0\1\u0120\65\0"+
    "\1\u0121\55\0\1\u0122\46\0\1\u0123\76\0\1\u0124\63\0"+
    "\1\u0125\74\0\1\u0126\63\0\1\u0127\60\0\1\u0128\42\0"+
    "\1\u0129\67\0\1\u012a\101\0\1\u012b\13\0\1\u012b\25\0"+
    "\1\u012c\63\0\1\u012d\101\0\1\u012e\66\0\1\u012f\55\0"+
    "\1\u0130\63\0\1\u0131\72\0\1\u0132\13\0\1\u0132\35\0"+
    "\1\u0133\24\0\1\u0133\44\0\1\u0134\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12636];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\1\1\6\11"+
    "\2\1\3\11\20\1\3\11\1\0\1\11\2\0\1\11"+
    "\30\0\1\11\5\0\1\11\2\0\2\1\1\0\1\11"+
    "\2\1\1\11\4\0\1\1\5\0\1\1\13\0\2\11"+
    "\10\0\1\11\5\0\1\11\24\0\2\11\6\0\1\1"+
    "\12\0\1\11\5\0\1\11\1\1\4\0\2\1\6\0"+
    "\1\11\2\0\1\11\15\0\1\11\5\0\1\11\2\0"+
    "\1\11\1\0\1\11\4\0\1\11\15\0\1\11\10\0"+
    "\1\11\2\0\1\11\3\0\2\11\1\0\1\11\3\0"+
    "\1\11\2\0\1\1\1\0\1\11\2\0\3\11\2\0"+
    "\1\11\5\0\2\11\4\0\1\11\4\0\1\11\10\0"+
    "\1\11\1\0\2\11\4\0\2\11\4\0\3\11\1\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[308];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      yyline = 1;        
    yycolumn = 1;    
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Este es un error lexico: "+yytext()+" , en la linea: "+yyline+", en la columna: "+yycolumn);
            }
            // fall through
          case 71: break;
          case 2:
            { 
            }
            // fall through
          case 72: break;
          case 3:
            { yycolumn=1;
            }
            // fall through
          case 73: break;
          case 4:
            { return new Symbol(sym.S_DOLLAR,yyline,yycolumn, yytext());
            }
            // fall through
          case 74: break;
          case 5:
            { return new Symbol(sym.PR_PARABRE,yyline,yycolumn, yytext());
            }
            // fall through
          case 75: break;
          case 6:
            { return new Symbol(sym.PR_PARCIERRA,yyline,yycolumn, yytext());
            }
            // fall through
          case 76: break;
          case 7:
            { return new Symbol(sym.PR_MULT,yyline,yycolumn, yytext());
            }
            // fall through
          case 77: break;
          case 8:
            { return new Symbol(sym.PR_SUMA,yyline,yycolumn, yytext());
            }
            // fall through
          case 78: break;
          case 9:
            { return new Symbol(sym.S_COMA,yyline,yycolumn, yytext());
            }
            // fall through
          case 79: break;
          case 10:
            { return new Symbol(sym.PR_RESTA,yyline,yycolumn, yytext());
            }
            // fall through
          case 80: break;
          case 11:
            { return new Symbol(sym.PR_DIV,yyline,yycolumn, yytext());
            }
            // fall through
          case 81: break;
          case 12:
            { return new Symbol(sym.ENTERO,yyline,yycolumn, yytext());
            }
            // fall through
          case 82: break;
          case 13:
            { return new Symbol(sym.S_PUNTOYCOMA,yyline,yycolumn, yytext());
            }
            // fall through
          case 83: break;
          case 14:
            { return new Symbol(sym.S_MAYORQ,yyline,yycolumn, yytext());
            }
            // fall through
          case 84: break;
          case 15:
            { return new Symbol(sym.S_INTERROGACIONCIERRA,yyline,yycolumn, yytext());
            }
            // fall through
          case 85: break;
          case 16:
            { return new Symbol(sym.S_LLAVEABRE,yyline,yycolumn, yytext());
            }
            // fall through
          case 86: break;
          case 17:
            { return new Symbol(sym.S_LLAVECIERRA,yyline,yycolumn, yytext());
            }
            // fall through
          case 87: break;
          case 18:
            { return new Symbol(sym.S_INTERROGACIONABRE, yyline, yycolumn, yytext());
            }
            // fall through
          case 88: break;
          case 19:
            { return new Symbol(sym.STRING, yyline, yycolumn, yytext());
            }
            // fall through
          case 89: break;
          case 20:
            { return new Symbol(sym.CHAR, yyline, yycolumn, yytext());
            }
            // fall through
          case 90: break;
          case 21:
            { return new Symbol(sym.PR_OR,yyline,yycolumn, yytext());
            }
            // fall through
          case 91: break;
          case 22:
            { return new Symbol(sym.PR_SI,yyline,yycolumn, yytext());
            }
            // fall through
          case 92: break;
          case 23:
            { return new Symbol(sym.DOUBLE,yyline,yycolumn, yytext());
            }
            // fall through
          case 93: break;
          case 24:
            { return new Symbol(sym.PR_AND,yyline,yycolumn, yytext());
            }
            // fall through
          case 94: break;
          case 25:
            { return new Symbol(sym.PR_CON,yyline,yycolumn, yytext());
            }
            // fall through
          case 95: break;
          case 26:
            { return new Symbol(sym.PR_FIN,yyline,yycolumn, yytext());
            }
            // fall through
          case 96: break;
          case 27:
            { return new Symbol(sym.PR_MOD,yyline,yycolumn, yytext());
            }
            // fall through
          case 97: break;
          case 28:
            { return new Symbol(sym.PR_NOT,yyline,yycolumn, yytext());
            }
            // fall through
          case 98: break;
          case 29:
            { return new Symbol(sym.IDENTIFICADOR, yyline, yycolumn, yytext());
            }
            // fall through
          case 99: break;
          case 30:
            { return new Symbol(sym.PR_COMO,yyline,yycolumn, yytext());
            }
            // fall through
          case 100: break;
          case 31:
            { return new Symbol(sym.PR_OSI,yyline,yycolumn, yytext());
            }
            // fall through
          case 101: break;
          case 32:
            { return new Symbol(sym.PR_PARA,yyline,yycolumn, yytext());
            }
            // fall through
          case 102: break;
          case 33:
            { return new Symbol(sym.PR_FALSO,yyline,yycolumn, yytext());
            }
            // fall through
          case 103: break;
          case 34:
            { return new Symbol(sym.PR_HACER,yyline,yycolumn, yytext());
            }
            // fall through
          case 104: break;
          case 35:
            { return new Symbol(sym.PR_HASTA,yyline,yycolumn, yytext());
            }
            // fall through
          case 105: break;
          case 36:
            { return new Symbol(sym.PR_MAYOR,yyline,yycolumn, yytext());
            }
            // fall through
          case 106: break;
          case 37:
            { return new Symbol(sym.PR_MENOR,yyline,yycolumn, yytext());
            }
            // fall through
          case 107: break;
          case 38:
            { return new Symbol(sym.PR_SEGUN,yyline,yycolumn, yytext());
            }
            // fall through
          case 108: break;
          case 39:
            { return new Symbol(sym.PR_CAD,yyline,yycolumn, yytext());
            }
            // fall through
          case 109: break;
          case 40:
            { return new Symbol(sym.PR_FINSI,yyline,yycolumn, yytext());
            }
            // fall through
          case 110: break;
          case 41:
            { return new Symbol(sym.PR_INICIO,yyline,yycolumn, yytext());
            }
            // fall through
          case 111: break;
          case 42:
            { return new Symbol(sym.PR_METODO,yyline,yycolumn, yytext());
            }
            // fall through
          case 112: break;
          case 43:
            { return new Symbol(sym.PR_NUM,yyline,yycolumn, yytext());
            }
            // fall through
          case 113: break;
          case 44:
            { return new Symbol(sym.PR_BOOL,yyline,yycolumn, yytext());
            }
            // fall through
          case 114: break;
          case 45:
            { return new Symbol(sym.PR_FUNCION,yyline,yycolumn, yytext());
            }
            // fall through
          case 115: break;
          case 46:
            { return new Symbol(sym.PR_REPETIR,yyline,yycolumn, yytext());
            }
            // fall through
          case 116: break;
          case 47:
            { return new Symbol(sym.PR_CAR,yyline,yycolumn, yytext());
            }
            // fall through
          case 117: break;
          case 48:
            { return new Symbol(sym.PR_EJECUTAR,yyline,yycolumn, yytext());
            }
            // fall through
          case 118: break;
          case 49:
            { return new Symbol(sym.PR_ENTONCES,yyline,yycolumn, yytext());
            }
            // fall through
          case 119: break;
          case 50:
            { return new Symbol(sym.PR_IGUAL,yyline,yycolumn, yytext());
            }
            // fall through
          case 120: break;
          case 51:
            { return new Symbol(sym.PR_FINPARA,yyline,yycolumn, yytext());
            }
            // fall through
          case 121: break;
          case 52:
            { return new Symbol(sym.PR_IMPRIMIR,yyline,yycolumn, yytext());
            }
            // fall through
          case 122: break;
          case 53:
            { return new Symbol(sym.PR_INGRESAR,yyline,yycolumn, yytext());
            }
            // fall through
          case 123: break;
          case 54:
            { return new Symbol(sym.PR_MIENTRAS,yyline,yycolumn, yytext());
            }
            // fall through
          case 124: break;
          case 55:
            { return new Symbol(sym.PR_POT,yyline,yycolumn, yytext());
            }
            // fall through
          case 125: break;
          case 56:
            { return new Symbol(sym.PR_RETORNAR,yyline,yycolumn, yytext());
            }
            // fall through
          case 126: break;
          case 57:
            { return new Symbol(sym.PR_CONVALOR,yyline,yycolumn, yytext());
            }
            // fall through
          case 127: break;
          case 58:
            { return new Symbol(sym.PR_FINSEGUN,yyline,yycolumn, yytext());
            }
            // fall through
          case 128: break;
          case 59:
            { return new Symbol(sym.PR_HASTAQUE,yyline,yycolumn, yytext());
            }
            // fall through
          case 129: break;
          case 60:
            { return new Symbol(sym.PR_VERDADERO,yyline,yycolumn, yytext());
            }
            // fall through
          case 130: break;
          case 61:
            { return new Symbol(sym.PR_FINMETODO,yyline,yycolumn, yytext());
            }
            // fall through
          case 131: break;
          case 62:
            { return new Symbol(sym.PR_FINFUNCION,yyline,yycolumn, yytext());
            }
            // fall through
          case 132: break;
          case 63:
            { return new Symbol(sym.PR_IMPRIMIRNL,yyline,yycolumn, yytext());
            }
            // fall through
          case 133: break;
          case 64:
            { return new Symbol(sym.PR_INCREMENTAL,yyline,yycolumn, yytext());
            }
            // fall through
          case 134: break;
          case 65:
            { return new Symbol(sym.PR_DIFERENTE,yyline,yycolumn, yytext());
            }
            // fall through
          case 135: break;
          case 66:
            { return new Symbol(sym.PR_FINMIENTRAS,yyline,yycolumn, yytext());
            }
            // fall through
          case 136: break;
          case 67:
            { return new Symbol(sym.PR_MAYOROIGUAL,yyline,yycolumn, yytext());
            }
            // fall through
          case 137: break;
          case 68:
            { return new Symbol(sym.PR_MENOROIGUAL,yyline,yycolumn, yytext());
            }
            // fall through
          case 138: break;
          case 69:
            { return new Symbol(sym.PR_CONPARAMETROS,yyline,yycolumn, yytext());
            }
            // fall through
          case 139: break;
          case 70:
            { return new Symbol(sym.PR_DELOCONTRARIO,yyline,yycolumn, yytext());
            }
            // fall through
          case 140: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
