
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMENTMULTI = 7;
  public static final int PR_MAYOROIGUAL = 24;
  public static final int IDENTIFICADOR = 2;
  public static final int PR_DELOCONTRARIO = 37;
  public static final int PR_FIN = 32;
  public static final int PR_HASTA = 44;
  public static final int PR_CONPARAMETROS = 56;
  public static final int PR_DIV = 17;
  public static final int PR_FINSEGUN = 42;
  public static final int PR_REPETIR = 51;
  public static final int PR_INICIO = 31;
  public static final int PR_MIENTRAS = 49;
  public static final int PR_MENOR = 23;
  public static final int PR_IMPRIMIR = 60;
  public static final int PR_METODO = 54;
  public static final int PR_FINFUNCION = 58;
  public static final int PR_IMPRIMIRLN = 61;
  public static final int PR_OSI = 38;
  public static final int PR_CON = 46;
  public static final int S_DOLLAR = 71;
  public static final int PR_MULT = 16;
  public static final int D_DIGITO = 64;
  public static final int PR_EJECUTAR = 59;
  public static final int PR_SEGUN = 40;
  public static final int PR_SI = 35;
  public static final int DOUBLE = 5;
  public static final int PR_SUMA = 14;
  public static final int PR_RESTA = 15;
  public static final int PR_PARCIERRA = 21;
  public static final int CADENACOMILLASDOBLES = 8;
  public static final int COMENTARIO = 6;
  public static final int PR_ENTONCES = 36;
  public static final int PR_INCREMENTAL = 48;
  public static final int STRINGS = 65;
  public static final int PR_CAR = 13;
  public static final int PR_RETORNAR = 53;
  public static final int PR_AND = 29;
  public static final int PR_FUNCION = 57;
  public static final int PR_INGRESAR = 33;
  public static final int ENTERO = 4;
  public static final int S_COMA = 66;
  public static final int PR_CAD = 11;
  public static final int PR_PARABRE = 20;
  public static final int CHAR = 3;
  public static final int PR_HASTAQUE = 52;
  public static final int PR_BOOL = 12;
  public static final int PR_MAYOR = 22;
  public static final int EOF = 0;
  public static final int S_MAYORQ = 67;
  public static final int PR_POT = 18;
  public static final int PR_CONVALOR = 34;
  public static final int PR_FINPARA = 45;
  public static final int PR_FALSO = 63;
  public static final int error = 1;
  public static final int S_INTERROGACIONCIERRA = 70;
  public static final int PR_NOT = 30;
  public static final int S_LLAVECIERRA = 73;
  public static final int PR_NUM = 10;
  public static final int PR_OR = 28;
  public static final int PR_DIFERENTE = 27;
  public static final int PR_MOD = 19;
  public static final int PR_HACER = 41;
  public static final int PR_FINMIENTRAS = 50;
  public static final int S_LLAVEABRE = 72;
  public static final int PR_FINSI = 39;
  public static final int STRING = 9;
  public static final int PR_VERDADERO = 62;
  public static final int S_PUNTOYCOMA = 68;
  public static final int PR_COMO = 47;
  public static final int S_INTERROGACIONABRE = 69;
  public static final int PR_FINMETODO = 55;
  public static final int PR_MENOROIGUAL = 25;
  public static final int PR_IGUAL = 26;
  public static final int PR_PARA = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "CHAR",
  "ENTERO",
  "DOUBLE",
  "COMENTARIO",
  "COMENTMULTI",
  "CADENACOMILLASDOBLES",
  "STRING",
  "PR_NUM",
  "PR_CAD",
  "PR_BOOL",
  "PR_CAR",
  "PR_SUMA",
  "PR_RESTA",
  "PR_MULT",
  "PR_DIV",
  "PR_POT",
  "PR_MOD",
  "PR_PARABRE",
  "PR_PARCIERRA",
  "PR_MAYOR",
  "PR_MENOR",
  "PR_MAYOROIGUAL",
  "PR_MENOROIGUAL",
  "PR_IGUAL",
  "PR_DIFERENTE",
  "PR_OR",
  "PR_AND",
  "PR_NOT",
  "PR_INICIO",
  "PR_FIN",
  "PR_INGRESAR",
  "PR_CONVALOR",
  "PR_SI",
  "PR_ENTONCES",
  "PR_DELOCONTRARIO",
  "PR_OSI",
  "PR_FINSI",
  "PR_SEGUN",
  "PR_HACER",
  "PR_FINSEGUN",
  "PR_PARA",
  "PR_HASTA",
  "PR_FINPARA",
  "PR_CON",
  "PR_COMO",
  "PR_INCREMENTAL",
  "PR_MIENTRAS",
  "PR_FINMIENTRAS",
  "PR_REPETIR",
  "PR_HASTAQUE",
  "PR_RETORNAR",
  "PR_METODO",
  "PR_FINMETODO",
  "PR_CONPARAMETROS",
  "PR_FUNCION",
  "PR_FINFUNCION",
  "PR_EJECUTAR",
  "PR_IMPRIMIR",
  "PR_IMPRIMIRLN",
  "PR_VERDADERO",
  "PR_FALSO",
  "D_DIGITO",
  "STRINGS",
  "S_COMA",
  "S_MAYORQ",
  "S_PUNTOYCOMA",
  "S_INTERROGACIONABRE",
  "S_INTERROGACIONCIERRA",
  "S_DOLLAR",
  "S_LLAVEABRE",
  "S_LLAVECIERRA"
  };
}

